### ISSUE TITLE
变量定义问题

### ISSUE THREAD

**Issue by tClown11** [zhoushuguang/beyond#46]
https://github.com/zhoushuguang/beyond/blob/b1af51cf7e186805b29fc9bd573aac625dd1b378/application/user/rpc/internal/model/usermodel.go#L34
在这个方法中的 userRows 表示的是什么意思，我没有找到这个变量定义的位置

**Comment by cpf2021-gif** [comment]
[userRows的定义](https://github.com/zhoushuguang/beyond/blob/b1af51cf7e186805b29fc9bd573aac625dd1b378/application/user/rpc/internal/model/usermodel_gen.go#L21)
这里的userRows是user表中所有的字段，效果跟`select *`是一样的
